# Start the service with the command 'docker-compose up -d'

version: '3.9'

services:
  mongo-psf-metrics:
    image: mongo:4.2.0
    container_name: mongo-psf-metrics
    ports:
      - '5555:27017' # <host port>:<container port>
    volumes:
      - ../data/database:/data/db
    command: mongod --logpath=/dev/null # -- quiet
    restart: always

  ipfs-psf-metrics:
    # https://github.com/christroutner/trickle-ipfs
    image: christroutner/trickle-ipfs:v1.0.1
    #build:
    #  context: ./
    #  dockerfile: Dockerfile
    container_name: ipfs
    environment:
      IPFS_DAEMON_ARGUMENTS: '--enable-pubsub-experiment --migrate=true --agent-version-suffix=docker --routing=dhtclient'
      UPLOAD_KBPS: '1000'
      DOWNLOAD_KBPS: '1000'
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '10'
    mem_limit: 2000mb
    ports:
      - 4001:4001
      - 4003:4003
      - 172.17.0.1:5001:5001
      - 172.17.0.1:8080:8080
    command: [
      './start-ipfs.sh'
    ]
    volumes:
      - ../data/go-ipfs/data:/root/.ipfs
    restart: always

  psf-metrics:
    build: .
    #image: christroutner/ipfs-service-provider:v2.2.13
    container_name: psf-metrics
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '10'
    mem_limit: 1000mb
    links:
      - mongo-psf-metrics
      - ipfs-psf-metrics
    ports:
      - '5010:5010' # <host port>:<container port>
    volumes:
      # - ../data/ipfsdata:/home/safeuser/ipfs-service-provider/.
      - ../../wallet.json:/home/safeuser/ipfs-service-metrics/wallet.json
      - ./start-production.sh:/home/safeuser/ipfs-service-metrics/start-production.sh
    restart: always
